
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 30 02:03:55 EDT 2017
//----------------------------------------------------

package formula.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTEGRAL = 37;
  public static final int FORALL = 20;
  public static final int POWER = 19;
  public static final int STR = 44;
  public static final int EMPTY = 41;
  public static final int UMINUS = 15;
  public static final int LPAREN = 31;
  public static final int MINUS = 14;
  public static final int RPAREN = 30;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int SETDEF = 27;
  public static final int LT = 10;
  public static final int NIN = 24;
  public static final int IN = 23;
  public static final int OR = 3;
  public static final int COMMA = 35;
  public static final int DIV = 18;
  public static final int GEQ = 11;
  public static final int NUM = 42;
  public static final int PLUS = 13;
  public static final int ID = 43;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int TRUE = 39;
  public static final int error = 1;
  public static final int MUL = 16;
  public static final int IMP = 5;
  public static final int EXISTS = 21;
  public static final int MOD = 17;
  public static final int NEQ = 8;
  public static final int EQ = 7;
  public static final int LBRACK = 29;
  public static final int COLON = 36;
  public static final int UNION = 25;
  public static final int LBRACE = 32;
  public static final int RBRACK = 28;
  public static final int DIFFERENTIAL = 38;
  public static final int EQUIV = 6;
  public static final int NEXISTS = 22;
  public static final int RBRACE = 33;
  public static final int LEQ = 12;
  public static final int DIFF = 26;
  public static final int FALSE = 40;
  public static final int GT = 9;
}

